package com.myspace.mydrooltest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String myField;

	public MyObject() {
	}

	public java.lang.String getMyField() {
		return this.myField;
	}

	public void setMyField(java.lang.String myField) {
		this.myField = myField;
	}

	public MyObject(java.lang.String myField) {
		this.myField = myField;
	}

}