package com.myspace.mydrooltest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MyObject() {
    }




}